{{- if and (.Values.grafanaLoki) (.Values.grafanaLoki.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/grafana-loki
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        loki:
        {{- toYaml .Values.grafanaLoki | nindent 10 }}
        test_pod:
          enabled: false
        promtail:
          enabled: false
        fluent-bit:
          enabled: false
        grafana:
          enabled: false
        prometheus:
          enabled: false
        filebeat:
          enabled: false
        logstash:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
