{{- if and (.Values.strimziTopicOperator) (.Values.strimziTopicOperator.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-topic-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/strimzi-topic-operator
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        strimzi-kafka-operator:
        {{- toYaml .Values.strimziTopicOperator | nindent 10 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: strimzi
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
