aws-for-fluent-bit:
  serviceAccount:
    create: false

  cloudWatch:
    enabled: true

  firehose:
    enabled: false

  kinesis:
    enabled: false

  elasticsearch:
    enabled: false

  additionalOutputs: |
    [OUTPUT]
        name          loki
        match         *
        host          loki-loki-distributed-ingester
        remove_keys   source
        labels        {job="fluent-bit"}
