aws-for-fluent-bit:
  serviceAccount:
    create: false

  cloudWatch:
    enabled: true

  firehose:
    enabled: false

  kinesis:
    enabled: false

  elasticsearch:
    enabled: false

  additionalOutputs: |
    [OUTPUT]
        Name          grafana-loki
        Match         *
        Url           http://loki-loki-distributed-ingester:3100/loki/api/v1/push
        RemoveKeys    source
        Labels        {job="fluent-bit"}
        LabelKeys     container_name
        BatchWait     1
        BatchSize     1001024
        LineFormat    json
        LogLevel      info
