aws-for-fluent-bit:
  serviceAccount:
    create: false

  cloudWatch:
    enabled: true

  firehose:
    enabled: false

  kinesis:
    enabled: false

  elasticsearch:
    enabled: false

  additionalOutputs: |
    [OUTPUT]
        name                      loki
        match                     *
        host                      loki-loki-distributed-distributor.grafana.svc.cluster.local
        labels                    job=fluentbit, stream=$stream
        auto_kubernetes_labels    on
